import assert from 'node:assert/strict'
import { mkdir } from 'node:fs/promises'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright')
const browser = await chromium.launch({ channel: 'chrome', headless: true })
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.clock.install()
  await page.goto(process.env.NERRO_TEST_URL || 'http://localhost:8080')
  const carousel = page.getByRole('region', { name: 'North-East landscapes and learning' })
  await carousel.scrollIntoViewIfNeeded()
  await carousel.locator('img').evaluateAll(images => Promise.all(images.map(image => image.decode())))
  assert.equal(await carousel.getByRole('heading').textContent(), 'Extraordinary landscapes. Essential journeys.')
  await carousel.hover()
  await page.clock.fastForward(10000)
  assert.equal(await carousel.getByRole('heading').textContent(), 'A moving Earth beneath the mountains.')
  await carousel.getByRole('button', { name: 'Pause slideshow' }).click()
  await page.clock.fastForward(20000)
  assert.equal(await carousel.getByRole('heading').textContent(), 'A moving Earth beneath the mountains.')
  await carousel.getByRole('button', { name: 'Play slideshow' }).click()
  await page.clock.fastForward(10000)
  assert.equal(await carousel.getByRole('heading').textContent(), 'When the rain changes, the journey can too.')
  await page.clock.fastForward(10000)
  assert.equal(await carousel.getByRole('heading').textContent(), 'Extraordinary landscapes. Essential journeys.')
  assert.equal(await carousel.getByRole('button', { name: 'Next story' }).count(), 0)
  await mkdir('../.local-tunnel/ui', { recursive: true })
  await carousel.screenshot({ path: '../.local-tunnel/ui/region-stories-desktop.png' })
  await page.setViewportSize({ width: 390, height: 844 })
  await carousel.screenshot({ path: '../.local-tunnel/ui/region-stories-mobile.png' })
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.reload()
  assert.equal(await carousel.getByRole('button', { name: 'Play slideshow' }).count(), 1)
  assert.deepEqual(errors, [])
  console.log('PASS: photographs, autoplay while hovered, pause/resume, wraparound, mobile overflow, reduced motion, browser errors')
} finally { await browser.close() }
